name: spatial-ar
data_dir: "/nakama/data"

logger:
  stdout: true
  level: "INFO"

session:
  token_expiry_sec: 7200  # 2 hours
  refresh_token_expiry_sec: 604800  # 7 days
  single_session: false

socket:
  server_key: "${NAKAMA_SERVER_KEY}"
  port: 7350
  address: "0.0.0.0"
  protocol: "tcp"
  max_message_size_bytes: 4096
  read_buffer_size_bytes: 4096
  write_buffer_size_bytes: 4096
  idle_timeout_ms: 60000
  write_wait_ms: 5000
  pong_wait_ms: 25000
  ping_period_ms: 15000
  ping_backoff_threshold: 20

api:
  port: 7350
  address: "0.0.0.0"
  
grpc:
  port: 7349
  address: "0.0.0.0"

runtime:
  http_key: "spatial_http_key_2024"
  read_only_globals: true
  lua_entrypoint: "main.lua"

tracker:
  event_queue_size: 8192
  event_queue_workers: 8

match:
  input_queue_size: 1024
  call_queue_size: 1024
  join_attempt_queue_size: 1024
  defer_message_fn: ""
  join_marker_deadline_ms: 15000
  max_players: 8  # Max players per AR session

console:
  port: 7351
  address: "0.0.0.0"
  username: "${NAKAMA_CONSOLE_USERNAME:-admin}"
  password: "${NAKAMA_CONSOLE_PASSWORD}"
  signing_key: "${NAKAMA_CONSOLE_SIGNING_KEY}"
  token_expiry_sec: 86400  # 24 hours

cluster:
  join: []
  max_message_size_bytes: 4096
  gossip_bindaddr: "0.0.0.0"
  gossip_bindport: 7352

database:
  address:
    - "postgres:5432"
  name: "${POSTGRES_DB:-spatial_platform}"
  user: "${POSTGRES_USER:-admin}"
  password: "${POSTGRES_PASSWORD}"
  ssl_mode: "require"
  ssl_cert: "/etc/ssl/certs/server.crt"
  ssl_key: "/etc/ssl/private/server.key"  
  ssl_ca: "/etc/ssl/certs/ca.crt"
  conn_max_lifetime_ms: 3600000
  max_idle_conns: 50
  max_open_conns: 100