global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nakama'
    static_configs:
      - targets: ['nakama:7350']
    metrics_path: '/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']