version: '3.8'

services:
  nakama:
    image: heroiclabs/nakama:3.18.0
    container_name: spatial-nakama
    depends_on:
      - nakama-db
      - nakama-redis
    command: >
      /nakama/nakama
      --database.address nakama-db:5432
      --database.name nakama
      --database.user nakama
      --database.password nakama
      --cache redis://nakama-redis:6379
      --socket.server_key spatial_platform_key_2024
      --runtime.http_key spatial_http_key_2024
      --console.username spatial_admin
      --console.password spatial_console_2024
      --runtime.path /nakama/data/modules
    ports:
      - "7349:7349"  # gRPC API
      - "7350:7350"  # HTTP API
      - "7351:7351"  # Console
    volumes:
      - ./nakama/data:/nakama/data
      - ./nakama/modules:/nakama/data/modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - spatial-network

  nakama-db:
    image: postgres:15-alpine
    container_name: spatial-nakama-db
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_USER=nakama
      - POSTGRES_PASSWORD=nakama
    volumes:
      - nakama_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nakama -d nakama"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - spatial-network

  nakama-redis:
    image: redis:7-alpine
    container_name: spatial-nakama-redis
    volumes:
      - nakama_redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spatial-network

volumes:
  nakama_postgres_data:
    driver: local
  nakama_redis_data:
    driver: local

networks:
  spatial-network:
    external: true