# OpenTelemetry Collector Configuration - Production
# Spatial Platform Telemetry Pipeline

receivers:
  # OTLP receiver for services
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost"
            - "http://localhost:3000" 
            - "http://localhost:*"

  # Prometheus metrics scraping
  prometheus:
    config:
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      scrape_configs:
        # Spatial AR services
        - job_name: 'spatial-gateway'
          static_configs:
            - targets: ['gateway:8000']
          metrics_path: '/metrics'
          scrape_interval: 10s
          
        - job_name: 'spatial-localization'
          static_configs:
            - targets: ['localization:8080']
          metrics_path: '/metrics'
          scrape_interval: 5s  # High frequency for AR performance
          
        - job_name: 'spatial-vps-engine'
          static_configs:
            - targets: ['vps-engine:9000']
          metrics_path: '/metrics'
          scrape_interval: 5s
          
        - job_name: 'spatial-cloud-anchors'
          static_configs:
            - targets: ['cloud-anchor-service:9004']
          metrics_path: '/metrics'
          scrape_interval: 10s
          
        - job_name: 'spatial-mapping'
          static_configs:
            - targets: ['mapping-processor:8080']
          metrics_path: '/metrics'
          scrape_interval: 30s
          
        # Infrastructure services
        - job_name: 'nakama'
          static_configs:
            - targets: ['nakama:9100']
          metrics_path: '/metrics'
          scrape_interval: 15s
          
        - job_name: 'postgres-cluster'
          static_configs:
            - targets: ['postgres-exporter:9187']
          metrics_path: '/metrics'
          scrape_interval: 30s
          
        - job_name: 'redis'
          static_configs:
            - targets: ['redis-exporter:9121']
          metrics_path: '/metrics'
          scrape_interval: 30s

  # Jaeger receiver for legacy traces
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268

  # Log receivers
  filelog:
    include:
      - /tmp/logs/*.log
    operators:
      - type: json_parser
        id: json_parser
        output: spatial_parser
      - type: regex_parser
        id: spatial_parser
        regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z) (?P<level>\w+) (?P<service>\w+) (?P<message>.*)'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%dT%H:%M:%S.%fZ'

processors:
  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 1024
    spike_limit_mib: 256
    check_interval: 1s

  # Batch processing for performance
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Resource processor for service identification
  resource:
    attributes:
      - key: service.namespace
        value: "spatial.platform"
        action: upsert
      - key: service.version
        from_attribute: "app.version"
        action: upsert
      - key: deployment.environment
        from_attribute: "ENVIRONMENT"
        action: upsert

  # Attribute processing for AR-specific metrics
  attributes:
    actions:
      # AR performance attributes
      - key: ar.session.id
        action: upsert
        from_attribute: session_id
      - key: ar.frame.rate
        action: upsert
        from_attribute: fps
      - key: ar.tracking.quality
        action: upsert
        from_attribute: tracking_quality
      - key: spatial.map.id
        action: upsert
        from_attribute: map_id
      - key: spatial.anchor.count
        action: upsert
        from_attribute: anchor_count

  # Probabilistic sampling for high-volume traces
  probabilistic_sampler:
    sampling_percentage: 10.0
    hash_seed: 42

  # Span processing for AR-specific data (2024 enterprise standard)
  span:
    name:
      # Update span names based on HTTP targets
      from_attributes: ["http.target", "http.method"]
      separator: " "
    # Note: Individual span renaming rules removed - use transform processor for complex logic

  # Filter processor for noise reduction
  filter:
    spans:
      # Filter out health check spans
      exclude:
        match_type: strict
        attributes:
          - key: http.target
            value: /health
          - key: http.target
            value: /metrics

exporters:
  # Prometheus metrics export
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "spatial"
    const_labels:
      platform: "spatial-ar"

  # Enterprise OTLP export to Jaeger (2024 standard - jaeger exporter deprecated)
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Enterprise OTLP HTTP export to Loki (2024 standard - loki exporter deprecated)
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: "spatial-platform"

  # Development/debugging exporters
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

  # File export for backup
  file:
    path: /tmp/otel/traces.json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 3

extensions:
  # Health check endpoint
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health

  # Performance profiling
  pprof:
    endpoint: 0.0.0.0:1777

  # Prometheus metrics for collector itself
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    # Metrics pipeline
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource, attributes]
      exporters: [prometheus, debug]

    # Enterprise traces pipeline (2024 standard)
    traces:
      receivers: [otlp, jaeger]
      processors: [memory_limiter, batch, resource, attributes, probabilistic_sampler, span, filter]
      exporters: [otlp/jaeger, debug]

    # Enterprise logs pipeline (2024 standard)
    logs:
      receivers: [otlp, filelog]
      processors: [memory_limiter, batch, resource, attributes]
      exporters: [otlphttp/loki, debug, file]

  # Telemetry for collector itself
  telemetry:
    logs:
      level: "info"
    metrics:
      level: detailed